"""empty message

Revision ID: 3fbee0c7648c
Revises: a7bf2061c52b
Create Date: 2022-04-08 23:39:07.078220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbee0c7648c'
down_revision = 'a7bf2061c52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
