"""empty message

Revision ID: 41378a164af5
Revises: 5c733d6f9701
Create Date: 2022-04-04 16:34:25.565866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41378a164af5'
down_revision = '5c733d6f9701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_plant_id_fkey', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'plant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_plant_id_fkey', 'favorites', 'plant', ['plant_id'], ['id'])
    # ### end Alembic commands ###
