"""empty message

Revision ID: a7bf2061c52b
Revises: ef65632ecf15
Create Date: 2022-04-08 22:57:07.459970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bf2061c52b'
down_revision = 'ef65632ecf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('plant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'plant_id')
    # ### end Alembic commands ###
