"""empty message

Revision ID: f32c170c4800
Revises: 3ff5197b3f97
Create Date: 2022-04-01 18:20:02.627356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32c170c4800'
down_revision = '3ff5197b3f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'fertilizer_req',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('plant', 'fertilizer_tips',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=700),
               existing_nullable=False)
    op.alter_column('plant', 'height',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('plant', 'light_exposure',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.alter_column('plant', 'most_suitable_location',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'plant_care_tips',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=700),
               existing_nullable=False)
    op.alter_column('plant', 'plant_details',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=700),
               existing_nullable=False)
    op.alter_column('plant', 'plant_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'poisonous',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=700),
               existing_nullable=False)
    op.alter_column('plant', 'size',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('plant', 'temperature',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('plant', 'water_req',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('plant', 'water_tips',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=700),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'water_tips',
               existing_type=sa.Text(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'water_req',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'temperature',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('plant', 'size',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('plant', 'poisonous',
               existing_type=sa.Text(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'plant_image',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'plant_details',
               existing_type=sa.Text(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'plant_care_tips',
               existing_type=sa.Text(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'most_suitable_location',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'light_exposure',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'height',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('plant', 'fertilizer_tips',
               existing_type=sa.Text(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('plant', 'fertilizer_req',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
